# -*- coding: utf-8 -*-
"""ml1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Va7TK8DmZG4iQNLg4NMhuUp6YmdGsA_u
"""

import numpy as np
import matplotlib.pyplot as plt
import cv2
import os
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from google.colab import drive
from google.colab import files

# Config
IMG_SIZE = (28, 28)
PCA_VAR_RET = 0.90
AUG_ANGLES = [-8, 8]
AUG_TRANSL = [-2, 2]

print("Mounting Google Drive...")
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')
print("Drive mount check complete.")

zip_path_drive = "/content/drive/My Drive/Handwritten_Digits_Copied.zip"
zip_path_local = "/content/Handwritten_Digits_Copied.zip"
dataset_local_dir = "/content/local_handwritten_digits_dataset"

print("Checking for zip file in Drive...")
if not os.path.exists(zip_path_drive):
    print(f"Error: Zip '{zip_path_drive}' not found.")
    exit()

print("Copying zip to local storage...")
!cp "{zip_path_drive}" "{zip_path_local}"

print("Unzipping dataset...")
if os.path.exists(dataset_local_dir):
    !rm -rf "{dataset_local_dir}"
os.makedirs(dataset_local_dir, exist_ok=True)
!unzip -o -q "{zip_path_local}" -d "{dataset_local_dir}"

unzipped_contents = os.listdir(dataset_local_dir)
expected_nested_folder = "Handwritten_Digits_Copied"
if expected_nested_folder in unzipped_contents and os.path.isdir(os.path.join(dataset_local_dir, expected_nested_folder)):
    dataset_root = os.path.join(dataset_local_dir, expected_nested_folder)
else:
    dataset_root = dataset_local_dir
    if not any(str(i) in unzipped_contents for i in range(10)) or not os.path.isdir(os.path.join(dataset_root, '0')):
        print(f"Error: Digit folders not found.")
        exit()

if not os.path.exists(dataset_root):
    print(f"Error: Dataset path '{dataset_root}' not found after unzip.")
    exit()

def proc_img_bw(img, target_s):
    if len(img.shape) == 3:
        img_g = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    else:
        img_g = img
    _, img_bw = cv2.threshold(img_g, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    img_res = cv2.resize(img_bw, target_s, interpolation=cv2.INTER_AREA)
    return img_res

def load_data(d_dir, target_s):
    imgs = []
    lbls = []
    for d_lbl in range(10):
        d_f_path = os.path.join(d_dir, str(d_lbl))
        if not os.path.exists(d_f_path):
            continue
        for fname in os.listdir(d_f_path):
            if fname.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
                img_p = os.path.join(d_f_path, fname)
                img = cv2.imread(img_p)
                if img is None:
                    continue
                p_img = proc_img_bw(img, target_s)
                imgs.append(p_img)
                lbls.append(d_lbl)
    return np.array(imgs), np.array(lbls)

def augment_img_f(image, angle_r, transl_r):
    aug_imgs = [image]
    h, w = image.shape[:2]
    center = (w // 2, h // 2)

    for angle in angle_r:
        M = cv2.getRotationMatrix2D(center, angle, 1.0)
        rotated = cv2.warpAffine(image, M, (w, h), flags=cv2.INTER_AREA, borderValue=0)
        aug_imgs.append(rotated)

    for dx in transl_r:
        for dy in transl_r:
            if dx == 0 and dy == 0: continue
            M = np.float32([[1, 0, dx], [0, 1, dy]])
            shifted = cv2.warpAffine(image, M, (w, h), flags=cv2.INTER_AREA, borderValue=0)
            aug_imgs.append(shifted)
    return aug_imgs

print("Loading initial images...")
init_imgs, init_lbls = load_data(dataset_root, IMG_SIZE)

if len(init_imgs) == 0:
    print("No images loaded.")
    exit()

print("Applying augmentation...")
aug_imgs_list = []
aug_lbls_list = []
for i, img in enumerate(init_imgs):
    a_imgs = augment_img_f(img, AUG_ANGLES, AUG_TRANSL)
    for a_img in a_imgs:
        aug_imgs_list.append(a_img)
        aug_lbls_list.append(init_lbls[i])

final_proc_imgs = np.array(aug_imgs_list)
all_aug_lbls = np.array(aug_lbls_list)

# --- MODIFIED PLOTTING SECTION ---
print("\naugmented image for each digit (0-9):")
plt.figure(figsize=(15, 3))
samples_shown_count = {i: 0 for i in range(10)}
plot_index = 1
for i in range(len(final_proc_imgs)):
    label = all_aug_lbls[i]
    if samples_shown_count[label] < 1:
        plt.subplot(1, 10, plot_index)
        plt.imshow(final_proc_imgs[i], cmap='gray')
        plt.title(f'Digit: {label}')
        plt.axis('off')
        samples_shown_count[label] += 1
        plot_index += 1
        if plot_index > 10:
            break
plt.suptitle(f"Sample Augmented Images ({IMG_SIZE[0]}x{IMG_SIZE[1]} pixels)")
plt.tight_layout(rect=[0, 0.03, 1, 0.85])
plt.show()
# --- END MODIFIED PLOTTING SECTION ---

X = final_proc_imgs.reshape(len(final_proc_imgs), -1)
y = all_aug_lbls

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

pca = PCA(n_components=PCA_VAR_RET, random_state=42)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

param_grid_svm = {'C': [1, 10], 'gamma': [0.01, 0.1], 'kernel': ['rbf']}
svm = SVC(random_state=42)
grid_search_svm = GridSearchCV(svm, param_grid_svm, cv=2, scoring='accuracy', n_jobs=-1, verbose=0)
grid_search_svm.fit(X_train_pca, y_train)

svm_classifier = grid_search_svm.best_estimator_

y_pred = svm_classifier.predict(X_test_pca)

conf_matrix = confusion_matrix(y_test, y_pred)
print("\nCM:")
print(conf_matrix)

recall = recall_score(y_test, y_pred, average=None, labels=range(10), zero_division=0)
precision = precision_score(y_test, y_pred, average=None, labels=range(10), zero_division=0)
f1_s = f1_score(y_test, y_pred, average=None, labels=range(10), zero_division=0)

print("\nMetrics per Digit:")
print(f"{'D':<8} | {'Recall':<15} | {'Prec':<10} | {'F1':<10}")
print("-" * 50)
for i in range(10):
    print(f"{i:<8} | {recall[i]:<15.4f} | {precision[i]:<10.4f} | {f1_s[i]:<10.4f}")

overall_acc = accuracy_score(y_test, y_pred)
print(f"\nOverall Acc: {overall_acc:.4f}")

print("\nUpload image for prediction:")
try:
    uploaded = files.upload()
    if not uploaded:
        print("No file uploaded. Skipping.")
    else:
        fname = next(iter(uploaded))
        img_to_pred = cv2.imread(fname)
        if img_to_pred is None:
            print(f"Error: Could not read '{fname}'.")
        else:
            final_p_img = proc_img_bw(img_to_pred, IMG_SIZE)
            flat_img = final_p_img.reshape(1, -1)
            flat_img_scaled = scaler.transform(flat_img)
            flat_img_pca = pca.transform(flat_img_scaled)
            pred = svm_classifier.predict(flat_img_pca)
            p_digit = pred[0]

            plt.figure(figsize=(10, 5))
            plt.subplot(1, 2, 1)
            plt.imshow(cv2.cvtColor(img_to_pred, cv2.COLOR_BGR2RGB))
            plt.title("Original")
            plt.axis('off')
            plt.subplot(1, 2, 2)
            plt.imshow(final_p_img, cmap='gray')
            plt.title(f"Processed | Pred: {p_digit}")
            plt.axis('off')
            plt.tight_layout()
            plt.show()
            print(f"\nPrediction: {p_digit}")

except Exception as e:
    print(f"Error during upload/prediction: {e}")
